In [51]:
import pandas as pd
import numpy as np

In [52]:
movies=pd.read_csv(r"C:\Users\Yug\OneDrive\Desktop\Movi recomandation system\tmdb_5000_movies.csv")
credits=pd.read_csv(r"C:\Users\Yug\OneDrive\Desktop\Movi recomandation system\tmdb_5000_credits.csv")

In [53]:
# mearging  datasets on basis of  titel of movies
movies=movies.merge(credits,on="title")

# Data Processing

In [54]:
#removing  unnescessory  features  
movies = movies[['id','title','overview','genres','keywords','cast','crew']]

In [55]:
print(movies.isnull().sum(),"\n duplicate  values \n", movies.duplicated().sum())
# onley overvies  have  some missing  values  since   onley  3  null values are present   so we will simpley   drom  thes   rows
movies.dropna(inplace=True)

id          0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64
 duplicate  values
 0

In [56]:
#  geners ,keywords feature  values  are in dictonarey format so we have to  change it 
# print(movies.iloc[0].genres)
import ast
def convert(itm):
    l=[]
    for x in ast.literal_eval(itm): 
        l.append(x["name"])
    return l
movies['genres'] = movies['genres'].apply(convert)
movies['keywords'] = movies['keywords'].apply(convert)
movies.head()

,id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [57]:
def convert3(text):
    L = []
    for i in ast.literal_eval(text):
        if len(L)<3:
            L.append(i['name'])
    return L 
movies['cast'] = movies['cast'].apply(convert)
movies.head()

,id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [58]:
#  we  did not need to  consider  entire  crew   information
ast.literal_eval(movies["crew"][0])
def fetch_director(text):
    L = []
    for i in ast.literal_eval(text):
        if i['job'] == 'Director':
            L.append(i['name'])
    return L 
movies['crew'] = movies['crew'].apply(fetch_director)

In [59]:
def collapse(L):
    L1 = []
    for i in L:
        L1.append(i.replace(" ",""))
    return L1
movies['cast'] = movies['cast'].apply(collapse)
movies['crew'] = movies['crew'].apply(collapse)
movies['genres'] = movies['genres'].apply(collapse)
movies['keywords'] = movies['keywords'].apply(collapse)

In [60]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [61]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']
new = movies.drop(columns=['overview','genres','keywords','cast','crew'])
new['tags'] = new['tags'].apply(lambda x: " ".join(x))
new.head()

,id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [62]:
new["tag"]=new["tags"].apply(lambda x:x.lower())
new

,id,title,tags,tag
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,following the death of district attorney harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca...","john carter is a war-weary, former military ca..."
...,...,...,...,...
4804,9367,El Mariachi,El Mariachi just wants to play his guitar and ...,el mariachi just wants to play his guitar and ...
4805,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...,a newlywed couple's honeymoon is upended by th...
4806,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...","""signed, sealed, delivered"" introduces a dedic..."
4807,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...,when ambitious new york attorney sam is sent t...
4808,25975,My Date with Drew,Ever since the second grade when he first saw ...,ever since the second grade when he first saw ...

In [63]:
# Text → Stemming → Vectorization

import snowballstemmer
stemmer=snowballstemmer.stemmer('english')
def stem_text(text):
    return " ".join(stemmer.stemWords(text.split()))
# Apply on dataframe FIRST
new['tags']=new['tags'].apply(stem_text)

# THEN vectorize
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000,stop_words='english')
vector=cv.fit_transform(new['tags']).toarray()

# cosine_similarity

In [67]:
from sklearn.metrics.pairwise import cosine_similarity
similarity=cosine_similarity(vector) # this  will calculate the  similarity of  each  vector  with other vector  
similarity.shape  # this will contin 4806 array of   4806 len which is  distance of  each  movi  with  other

(4806, 4806)

In [68]:
similarity[0] #  this  will be similarity of  movi one with  other  movies

array([1.        , 0.06666667, 0.0745356 , ..., 0.0439587 , 0.        ,
       0.        ], shape=(4806,))

In [69]:
idx_titl={}
for i,x in enumerate(new["title"]):
    idx_titl[x]=i

In [70]:
def recommend(movi,k=5):  #O(nlogn + k)==O(nlogn)  #  we can use heap in order to  descreas  time complexity  to  (O(n*log k))
    idx=idx_titl[movi]    #O(1)
    distances=similarity[idx]
    movies_list=sorted(list(enumerate(distances)), reverse=True, key=lambda x: x[1])   #o(nlogn)
    res=[]
    for x in movies_list[1:min(k+1,len(idx_titl))]:  #O(k)
        res.append(new["title"][x[0]])
    return res
recommend("Avatar",5)

['Aliens vs Predator: Requiem',
 'Battle: Los Angeles',
 'Titan A.E.',
 'Predator',
 'Anne of Green Gables']

In [ ]:
new.to_csv("movies.csv")

In [73]:
import pickle
pickle.dump(similarity,open('similarity.pkl','wb'))